services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${password}
      POSTGRES_DB: ${db_name}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${user} -d ${db_name}"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s

  app:
    build: .
    container_name: streamlit_app
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: streamlit run BostonBnBApp.py --server.port=8501 --server.address=0.0.0.0

volumes:
  postgres_data:
